// Natal chart interpretations: what each planet in each sign means for the individual.

const interpretations: Record<string, Record<string, string>> = {
  Sun: {
    Aries: "A bold, pioneering spirit. You lead with courage and thrive on fresh starts. Impatient at times, but your infectious enthusiasm inspires those around you.",
    Taurus: "Grounded and sensual, you seek stability and beauty in all things. Your patience is legendary, though stubbornness can be your shadow side.",
    Gemini: "Curious and quick-witted, you're a natural communicator who thrives on variety. Restlessness drives you to learn constantly, but focus can be elusive.",
    Cancer: "Deeply nurturing and intuitive, you lead with your heart. Home and family are your anchors, and your emotional intelligence is a quiet superpower.",
    Leo: "Radiant and generous, you were born to shine. Creative self-expression fuels you, and loyalty to your loved ones runs deep.",
    Virgo: "Analytical and service-oriented, you find meaning in improving the world around you. Your eye for detail is unmatched, though self-criticism can hold you back.",
    Libra: "Charming and diplomatic, you seek harmony and fairness in every interaction. Relationships are central to your identity, and beauty moves your soul.",
    Scorpio: "Intensely perceptive and emotionally powerful, you navigate life's depths fearlessly. Transformation is your constant companion, and your willpower is formidable.",
    Sagittarius: "Adventurous and philosophical, you're driven by a hunger for truth and freedom. Your optimism is contagious, and your vision stretches far beyond the horizon.",
    Capricorn: "Ambitious and disciplined, you build lasting legacies through sheer determination. You respect tradition but quietly reshape it to serve your goals.",
    Aquarius: "Independent and visionary, you march to your own rhythm. Humanitarian ideals drive you, and your originality often puts you ahead of your time.",
    Pisces: "Compassionate and deeply imaginative, you feel the world's joys and sorrows as your own. Your creativity and intuition border on the mystical.",
  },
  Moon: {
    Aries: "Your emotions are quick and fiery. You need independence even in intimacy, and process feelings through action rather than reflection.",
    Taurus: "Emotionally steady and comfort-seeking. You feel safest in familiar routines, and physical touch and good food are how you self-soothe.",
    Gemini: "You process emotions through conversation and analysis. Emotional variety keeps you stimulated, though it can be hard to sit with heavy feelings.",
    Cancer: "Profoundly empathic, your moods ebb and flow like the tides. You nurture instinctively and need a safe emotional sanctuary to retreat to.",
    Leo: "Your emotional life is warm and dramatic. You need to feel appreciated and special, and you express care through grand, generous gestures.",
    Virgo: "You show love through acts of service and quiet devotion. Anxiety can manifest as over-analysis, but your caring nature is deeply reliable.",
    Libra: "Emotional equilibrium is essential to your wellbeing. You process feelings through partnership and can absorb others' emotions easily.",
    Scorpio: "Emotionally intense and private. You feel everything at full depth, forming powerful bonds but guarding your vulnerabilities fiercely.",
    Sagittarius: "You need emotional freedom and adventure. Optimism is your default setting, and you heal through exploration, humour, and philosophical perspective.",
    Capricorn: "Emotionally reserved but deeply loyal. You may struggle to express vulnerability, but your commitment to those you love is unwavering.",
    Aquarius: "You approach emotions with detachment and rationality. You need intellectual stimulation in close relationships and value emotional independence.",
    Pisces: "Boundlessly empathic and dreamy, you absorb the feelings around you like a sponge. Creative outlets and solitude are essential for emotional balance.",
  },
  Mercury: {
    Aries: "You think fast and speak directly. Your mind is decisive and competitive, always ready with a quick retort or bold idea.",
    Taurus: "A deliberate, practical thinker. You take your time forming opinions, but once set, your ideas are solid and grounded in reality.",
    Gemini: "Your mind is a hummingbird — brilliant, adaptable, and endlessly curious. You juggle multiple ideas effortlessly and communicate with natural charm.",
    Cancer: "You think with your heart. Memory and intuition guide your reasoning, and you communicate with empathy and emotional nuance.",
    Leo: "A confident, dramatic communicator. You speak with authority and flair, and your ideas carry warmth and creative vision.",
    Virgo: "Precise, analytical, and methodical. Your mind excels at problem-solving, and you communicate with clarity and attention to detail.",
    Libra: "A diplomatic thinker who weighs all sides carefully. You communicate with grace and seek intellectual harmony in discussions.",
    Scorpio: "Your mind probes beneath surfaces. You're drawn to hidden truths and communicate with penetrating insight and strategic precision.",
    Sagittarius: "A big-picture thinker with a philosophical bent. You communicate with enthusiasm and honesty, sometimes bluntly so.",
    Capricorn: "Structured and strategic in thought. You communicate with authority and pragmatism, always considering the practical implications.",
    Aquarius: "An innovative, unconventional thinker. Your ideas are often ahead of their time, and you communicate with intellectual independence.",
    Pisces: "An imaginative, intuitive mind. You think in images and feelings rather than logic, and your communication style is poetic and empathic.",
  },
  Venus: {
    Aries: "You love passionately and impulsively. The chase thrills you, and you're attracted to bold, independent partners who match your fire.",
    Taurus: "Deeply sensual and loyal in love. You value stability, physical affection, and the finer things — and you give generously to those you adore.",
    Gemini: "You're attracted to wit and mental stimulation. Flirtatious and playful, you need variety and conversation to keep love alive.",
    Cancer: "You love with nurturing devotion. Emotional security is everything, and you create warm, protective bonds with your loved ones.",
    Leo: "Romantic, generous, and dramatic in love. You want to be adored and you adore in return — with grand gestures and unwavering loyalty.",
    Virgo: "You show love through thoughtful acts of service. You're selective and modest in romance, but your devotion runs deep and true.",
    Libra: "A natural romantic who lives for partnership. Beauty, balance, and harmony are your love languages, and you charm effortlessly.",
    Scorpio: "You love with volcanic intensity. All-or-nothing in relationships, you crave deep emotional and physical merging with your partner.",
    Sagittarius: "You need freedom within love. Adventure, humour, and shared philosophies bond you to partners who respect your independence.",
    Capricorn: "You approach love with maturity and commitment. You're reserved at first, but your loyalty and devotion deepen steadily over time.",
    Aquarius: "You value friendship and intellectual connection in love. Unconventional relationships appeal to you, and you need space to be yourself.",
    Pisces: "A dreamy, selfless lover. You idealise your partners and experience love as a transcendent, almost spiritual force.",
  },
  Mars: {
    Aries: "Your drive is fierce and direct. You act on impulse, compete with intensity, and channel anger into immediate, decisive action.",
    Taurus: "Slow to anger but immovable once provoked. Your determination is bulldozer-strong, and you pursue goals with patient, relentless effort.",
    Gemini: "You channel energy into communication and multitasking. Verbal sparring energises you, and you pursue goals through wit and adaptability.",
    Cancer: "Your drive is emotionally fuelled. You fight fiercely for family and home, and your protective instincts are your greatest strength.",
    Leo: "Confident and commanding in action. You pursue goals with dramatic flair and creative passion, and your willpower is theatrical but genuine.",
    Virgo: "Precise and methodical in action. You channel drive into perfecting your craft, and your work ethic is quietly formidable.",
    Libra: "You act with diplomacy and seek fair outcomes. Conflict is uncomfortable, so you channel aggression into negotiation and strategic charm.",
    Scorpio: "Intensely focused and strategic. Your willpower is extraordinary, and you pursue your desires with relentless, laser-like determination.",
    Sagittarius: "Adventurous and enthusiastic in action. You chase goals with infectious optimism and boundless energy, though follow-through can waver.",
    Capricorn: "Disciplined and ambitious in pursuit. You climb steadily toward your goals with pragmatic focus and impressive self-control.",
    Aquarius: "You fight for ideals and innovation. Your actions are motivated by humanitarian vision, and you resist conformity with quiet rebellion.",
    Pisces: "Your drive is guided by intuition and compassion. You act on behalf of others and channel energy through creative and spiritual pursuits.",
  },
  Jupiter: {
    Aries: "You grow through bold initiative and leadership. Taking risks expands your world, and your faith in yourself is your greatest asset.",
    Taurus: "Abundance comes through patience and material wisdom. You attract prosperity naturally and find growth in building something lasting.",
    Gemini: "You expand through learning and communication. Knowledge is your currency, and your curiosity opens doors everywhere you go.",
    Cancer: "Growth flows through emotional connections and family. Your generosity toward loved ones returns to you tenfold.",
    Leo: "You grow through creative expression and generosity. Your natural confidence attracts opportunities, and joy is your compass.",
    Virgo: "Expansion comes through service and skillful work. Your attention to detail and desire to help others creates meaningful abundance.",
    Libra: "You grow through partnership and social grace. Fairness and beauty are your guiding principles, and relationships bring your greatest blessings.",
    Scorpio: "Deep transformation is your path to growth. You gain wisdom through crisis and rebirth, emerging stronger each time.",
    Sagittarius: "A natural explorer and truth-seeker. Travel, philosophy, and higher education expand your world in the most fulfilling ways.",
    Capricorn: "You grow through discipline and long-term vision. Success comes slowly but substantially — your ambition is rewarded with lasting achievement.",
    Aquarius: "Innovation and community are your growth engines. You expand by challenging convention and championing progressive ideas.",
    Pisces: "Spiritual depth and compassion are your gifts. You grow through faith, artistic expression, and selfless service to others.",
  },
  Saturn: {
    Aries: "Your life lesson is learning patience with your impulses. Mastering self-discipline transforms raw courage into enduring leadership.",
    Taurus: "You're challenged to find security within rather than through possessions. True stability comes from inner resourcefulness.",
    Gemini: "Your lesson is depth over breadth. Disciplining your mind to focus brings the mastery your scattered curiosity craves.",
    Cancer: "Emotional self-sufficiency is your challenge. Building inner security frees you from dependency and unlocks profound nurturing wisdom.",
    Leo: "You learn humility alongside confidence. Earning recognition through genuine effort rather than seeking applause builds lasting self-worth.",
    Virgo: "Perfectionism is both your gift and burden. Learning to accept imperfection while maintaining high standards is your lifelong balancing act.",
    Libra: "Commitment in relationships is your growth edge. Learning to maintain your identity within partnership brings hard-won harmony.",
    Scorpio: "You're called to confront deep fears and power dynamics. Mastering emotional control without suppression brings tremendous inner strength.",
    Sagittarius: "Your lesson is grounding your idealism in reality. Disciplined pursuit of truth yields genuine wisdom rather than shallow beliefs.",
    Capricorn: "Structure and ambition come naturally, but learning to soften your drive with compassion and rest is your deeper challenge.",
    Aquarius: "Your challenge is balancing individuality with responsibility to community. Structured innovation creates lasting change.",
    Pisces: "Boundaries are your greatest lesson. Learning where you end and others begin transforms compassion from self-sacrifice into true service.",
  },
  Uranus: {
    Aries: "A revolutionary spirit. Your generation brings sudden, bold changes to how individuality and leadership are expressed in the world.",
    Taurus: "Your generation revolutionises values, finances, and relationship to the earth. Expect disruption in how we define security and wealth.",
    Gemini: "Innovation in communication and technology marks your generation. You reshape how information flows and how minds connect.",
    Cancer: "Your generation transforms family structures and emotional norms. New models of home and belonging emerge through you.",
    Leo: "Creative revolution defines your generation. You disrupt entertainment, self-expression, and how identity is performed publicly.",
    Virgo: "Your generation innovates health, work, and daily systems. Technology and efficiency are revolutionised through your collective energy.",
    Libra: "Your generation transforms relationships and social justice. New paradigms of partnership and equality emerge through you.",
    Scorpio: "Psychological and financial revolution marks your generation. You expose hidden powers and transform how society handles shared resources.",
    Sagittarius: "Your generation disrupts education, religion, and global perspectives. New philosophies and ways of seeking truth emerge.",
    Capricorn: "Your generation restructures institutions and governance. Old power structures are dismantled and rebuilt more equitably.",
    Aquarius: "Your generation embodies radical innovation and humanitarian vision. Technology and collective consciousness evolve rapidly through you.",
    Pisces: "Spiritual and artistic revolution defines your generation. Boundaries between reality and imagination dissolve, birthing new forms of empathy.",
  },
  Neptune: {
    Aries: "Your generation dreams of bold new beginnings. Spiritual identity and visionary leadership emerge as collective themes.",
    Taurus: "Your generation reimagines beauty, nature, and material values. A longing for sustainable, earth-connected spirituality defines you.",
    Gemini: "Your generation dissolves boundaries in communication. New media and fluid identities reshape how truth and stories are shared.",
    Cancer: "Your generation idealises home, heritage, and emotional connection. Nostalgia and collective empathy run deep.",
    Leo: "Your generation dreams through creative expression. Glamour, performance, and the blurring of art with identity define your era.",
    Virgo: "Your generation seeks spiritual meaning in service and health. Holistic healing and mindful daily practice become collective ideals.",
    Libra: "Your generation dreams of perfect love and social harmony. Idealistic relationships and aesthetic movements flourish in your era.",
    Scorpio: "Your generation plunges into psychological and spiritual depths. Fascination with mystery, the occult, and transformation runs deep.",
    Sagittarius: "Your generation idealises freedom, travel, and multicultural understanding. Spiritual seeking and global consciousness define you.",
    Capricorn: "Your generation brings visionary ambition and dreams of restructuring society. Idealism meets pragmatism in your collective mission.",
    Aquarius: "Your generation dissolves boundaries between technology and spirituality. Collective consciousness and digital empathy define your era.",
    Pisces: "Your generation embodies peak spiritual sensitivity and artistic imagination. Compassion and creative vision are your collective gifts.",
  },
  Pluto: {
    Aries: "Your generation transforms through radical individualism. New paradigms of courage, identity, and personal power emerge.",
    Taurus: "Your generation transforms values, economics, and humanity's relationship with the earth in profound, irreversible ways.",
    Gemini: "Your generation transforms communication and information. The power of words and ideas reshapes civilisation.",
    Cancer: "Your generation transforms family, nationalism, and emotional expression. Deep collective healing of ancestral wounds occurs.",
    Leo: "Your generation transforms creative power and leadership. Celebrity culture and individual expression undergo radical evolution.",
    Virgo: "Your generation transforms health, work, and environmental consciousness. Systems of daily life are overhauled.",
    Libra: "Your generation transforms relationships, law, and social contracts. Deep reformation of how people relate to each other unfolds.",
    Scorpio: "Your generation wields raw transformative power. Psychology, sexuality, and hidden institutional forces are exposed and reshaped.",
    Sagittarius: "Your generation transforms belief systems, education, and global culture. Old dogmas crumble as new truths emerge.",
    Capricorn: "Your generation dismantles and rebuilds power structures, governments, and corporations. Accountability becomes non-negotiable.",
    Aquarius: "Your generation transforms technology, community, and collective consciousness. Revolutionary social change accelerates.",
    Pisces: "Your generation transforms spirituality, art, and collective empathy. The dissolution of old illusions makes way for deeper compassion.",
  },
};

export function getNatalInterpretation(planet: string, sign: string): string {
  return interpretations[planet]?.[sign] || `${planet} in ${sign} colours your experience in unique and personal ways.`;
}
